spring:
  application:
    name: discovery-server
server:
  port: 8761
eureka:
  dashboard:
    enabled: true
  instance:
    hostname: localhost
    appname: ${spring.application.name}
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    eviction-interval-timer-in-ms: 30000